### ISSUE TITLE
Controller lookup doesn't work for Piraeus deployments

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/kubectl-linstor#2]
The kubectl command `kubectl get linstorcontrollers.linstor.linbit.com --all-namespaces` doesn't work for our Piraeus deployment. However, if you use `kubectl get linstorcontrollers --all-namespaces` instead, it works perfectly.

Locally I've changed https://github.com/piraeusdatastore/kubectl-linstor/blob/master/kubectl-linstor.go#L124. After that the kubectl plugin works as expected :-)

Thank you @WanzenBug for another great and useful tool!

**Comment by WanzenBug** [comment]
Thanks for pointing that out.

That's what you get for only testing in-house :sweat_smile:

**Comment by phoenix-bjoern** [comment]
Your PR was faster than mine ;-)
Thanks for the super fast response!
