### ISSUE TITLE
error: arguments in resource/name form must have a single resource and name

### ISSUE THREAD

**Issue by giovannicandido** [piraeusdatastore/kubectl-linstor#7]
running the command: `kubectl linstor node list`

I got the error:

error: arguments in resource/name form must have a single resource and name

kubectl version

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"434423f05465c7649ca038ad163f5d3b256e7ea6", GitTreeState:"clean", BuildDate:"2023-05-23T16:47:36Z", GoVersion:"go1.19.6 A1727 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

**Comment by giovannicandido** [comment]
I can' use the command line either:

`kubectl -n piraeus-datastore exec -it deployment/piraeus-operator-controller-manager -- linstor node list`

ERRO[0000] exec failed: unable to start container process: exec: "linstor": executable file not found in $PATH
command terminated with exit code 255

**Comment by giovannicandido** [comment]
Never mind my cluster is not fully installed. Closing this as I need to install the cluster first

**Comment by RD1007** [comment]
@giovannicandido I am having the same issue what cluster did you install first and how did that fix it

**Comment by LennyLip** [comment]
For googlers: This error raised when there is no one LinstorCluster created.

https://github.com/piraeusdatastore/piraeus-operator/tree/v2

```
$ kubectl apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
EOF
```
